### ISSUE TITLE
Sync serverside config to client.

### ISSUE THREAD

**Issue by Yorkforce** [planetguy32/Gizmos#17]
Noticed an issue when changing the following in the servers planetguy_Gizmos.cfg (not the one in the planetguyLib folder)
    B:enableSimpleSetSpawn=false

The client still behaves as though it's =true, which results in the chat message regarding 'Spawn reset to Pos' still being displayed even though the option is actually disabled serverside.

Changing the config on the client side fixes the issue.

Anyway it can be changed so the client uses the serverside config?

**Comment by planetguy32** [comment]
I should probably disable sending the chat message client-side, since clients alone can't set their spawn.
